hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  - model: model1
  - enhancement: 
    - default
  - _self_

base:
  image_suffix: png
  seed: 34
  batch_size: 16
  n_workers: 11
  image_size: 256

dagshub:
  repository_name: NIH-ChestXRay
  repository_owner: imonteiroyh
  tracking_uri: https://dagshub.com/imonteiroyh/NIH-ChestXRay.mlflow

reports:
  enhancement: reports/enhancement

data:
  rsua_segmentation:
    raw_path: "data/raw/Data Thorax DICOM RSUA (Validated)"
  nih_classification:
    raw_path: "data/raw/NIH Chest X-Ray"
    train_validation_samples: data/raw/NIH Chest X-Ray/train_val_list.txt
    test_samples: data/raw/NIH Chest X-Ray/test_list.txt 
  chestxray2017_classification:
    raw_path: "data/raw/chest_xray"
  raw: 
    path: data/raw
  interim: 
    path: data/interim
  processed:
    path: data/processed